# -*- coding: utf-8 -*-
"""FinalLab1_Imperial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H00hhjyMfEsvXTbu-0jav3iHNhhXUimp
"""

# De La Salle University – Dasmariñas
# S-ITCS227LA — Application Development and Emerging Technologies (Laboratory)

# Luis Anton P. Imperial
# BCS22

# Finals Laboratory Activity No. 1
# File Access In Python

# Given the text file, write a program that reads the numbers
# from the file. Find the minimum number, maximum number,
# length of the list, and sum of the numbers. The program should
# print all the numbers, and display the minimum number,
# maximum number, length of the list, and the total when all the
# numbers have been added together. (Warning! The input from
# the file will be considered a string. Be sure to convert the input
# to int or float – just as you do when numbers are entered from
# the keyboard.)
# Note: Save the file to “FinalLab1_Surname” Include the
# screenshots of the code, output, and text file. Attach also
# the .txt and .py files

from google.colab import drive
drive.mount('/gdrive')

grades = open('/gdrive/My Drive/Documents/Reference Documents/BCS2 ITCS227LA/Numbers.txt')

class grade_analysis():
  def __init__(self, grade_list):
    self.grades = grade_list
    self.grades_marked = []

  def get_grades(self, grades, grades_marked):
    for grade in grades:
      grades_marked.append(int(grade))
    return grades_marked

  def get_min_grade(self, grades_marked):
    return min(grades_marked)

  def get_max_grade(self, grades_marked):
    return max(grades_marked)

  def get_grade_count(self, grades_marked):
    return len(grades_marked)

  def get_grade_total(self, grades_marked):
    return sum(grades_marked)

  def analyze(self):
    grades_marked = self.get_grades(self.grades, self.grades_marked)

    print("Your grades are:", grades_marked)
    print("Your highest grade is:", self.get_min_grade(grades_marked))
    print("Your lowest grade is:", self.get_max_grade(grades_marked))
    print("Your number of grades is:", self.get_grade_count(grades_marked))
    print("Your total grade is:", self.get_grade_total(grades_marked))

def main():
  grade_analyzer = grade_analysis(grades)
  grade_analyzer.analyze()

main()